<div id="brands_list_box">
    <h3>合作商品牌列表</h3>
    <hr>
</div>

<?php
 //获取pub/media目录的url
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
 $brandsList = $block->getBrandsList();

 foreach($brandsList as $brand){?>

 <div class="brand-box">
    <img src="<?= $mediaUrl.$brand['img']?>">
    <p>品牌名称：<?= $brand['name'] ?></p>
    <p>品牌描述：<?= $brand['description'] ?></p>
 </div>

 <?php }?>


 <style>
    .brand-box{
        width:300px;
        height:auto;
        float:left;
        margin-right:20px;
        margin-bottom:20px;
    }
 </style>