<?php
/** \ExampleCorp\Learning\Block\Widget\Test $block */
$bannerImg = $this->getViewFileUrl('Lyh_Banner::images/banners/banner.png');
$timeConfig = $this->helper('Lyh\Banner\Helper\Data')->getTimeSaleConfig();

?>
<style>
#banner-img{
    width:100%;
    height:300px;
}
</style>
<div class="banner-container">
    <h3>这个模板来自于主题目录.</h3>
    <img id='banner-img' src="<?=$bannerImg?>">

    <div>
        <button id='btn'>点击事件</button>
    </div>

</div>


<!-- 显示读取的配置项 -->
<div id='hot-sale-title'>
    <h2 class="time-sale-heading">
        <span>限时促销时间:</span>
        <span><?=$timeConfig['s_day']?><time>,<?=$timeConfig['s_time']?>--<?=$timeConfig['e_day']?>,<?=$timeConfig['e_time']?></span>
    </h2>
</div>

<script>
require([
        'jquery',
        'banner' //引入banner.js
], function($,banner) {
    $("#btn").click(function(){
        alert('按钮点击事件被触发了');
    })
})
</script>